my_string = input("Наберите текст: ")
number_of_characters = len(my_string)
print("В вашем тексте ", number_of_characters, " символов")
my_string_1 = input("Наберите текст по второй части задания №1: ")
print("Результат: ", my_string_1.upper())
my_string_1 = input("Наберите текст по второй части задания №2: ")
print("Результат: ", my_string_1.lower())
my_string_1 = input("Наберите текст по второй части задания №3: ")
print("Результат: ", my_string_1.replace(" ",""))
my_string_1 = input("Наберите текст по второй части задания №4: ")
print("Результат: ", my_string_1[0])
my_string_1 = input("Наберите текст по второй части задания №5: ")
print("Результат: ", my_string_1[-1])